spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: F
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      flyway:
        url: jdbc:mariadb://localhost:3306/product-manager
        schemas: product-manager
        user: "root"
        password: "F"